# Generated by Django 4.0.8 on 2023-09-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_name', models.CharField(max_length=200, verbose_name='犬名')),
                ('image', models.ImageField(upload_to='photos', verbose_name='イメージ')),
                ('comment', models.TextField(verbose_name='コメント')),
            ],
        ),
    ]
