# Generated by Django 4.0.8 on 2023-09-06 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dogapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_1', models.IntegerField(verbose_name='回答1')),
                ('answer_2', models.IntegerField(verbose_name='回答2')),
                ('answer_3', models.IntegerField(verbose_name='回答3')),
                ('answer_4', models.IntegerField(verbose_name='回答4')),
                ('answer_5', models.IntegerField(verbose_name='回答5')),
                ('answer_6', models.IntegerField(verbose_name='回答6')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_1', models.IntegerField(verbose_name='質問1')),
                ('question_2', models.IntegerField(verbose_name='質問2')),
                ('question_3', models.IntegerField(verbose_name='質問3')),
                ('question_4', models.IntegerField(verbose_name='質問4')),
                ('question_5', models.IntegerField(verbose_name='質問5')),
                ('question_6', models.IntegerField(verbose_name='質問6')),
                ('dog_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogapp.dogs', verbose_name='犬名')),
            ],
        ),
    ]
