# Generated by Django 4.0.8 on 2023-09-21 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogapp', '0005_alter_comment_category_alter_comment_comment_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='dogapp.dogs', verbose_name='犬名'),
        ),
    ]
